### ISSUE TITLE
Dismantling

### ISSUE THREAD

**Issue by Siryphas** [Stexinator/TheWitcherTRPG#102]
In the Crafting rules, you can dismantle an item to get 1/2 of the components made to construct it (minimum of 1). I was wondering if there was a way to use the Real Craft system to do this. Real Craft will remove the required components and then add the item to the inventory, is there a way to reverse this, with half the component?

**Comment by Stexinator** [comment]
I dont see it at Real Craft but more in a context/header menu. The problem is that most items dont have their crafting materials associated. So the information which components are used is not present

**Comment by Siryphas** [comment]
In my compendium, each of the diagrams have the material components in there, tied to what they make. So when Real Craft is used, it knows which materials to pull out of the character sheet and what item to add. It could be possible to reverse engineer that coding to do the opposite

**Comment by Stexinator** [comment]
To reverse engineer I would need to:

-  look up all crafting recipes
- check each recipe if it creates an item with the same name (name matching should be enough here, wont respect upgrades etc)
- check the resources needed for the craft
- half it (minimum 1)
- add it to the character

the last 2 things are a non-issue. The lookup is quite problematic due to the point of compendia is that they are not available all the time.

I could introduce the needed materials to items and automatically write it into them when they are crafted, but that would not solve the problems with already existing items or from the compedium.
