### ISSUE TITLE
[Feature] Add sub-inventories for containers

### ISSUE THREAD

**Issue by Stexinator** [Stexinator/TheWitcherTRPG#46]
Containers should have drag and droppable sub-inventories

**Comment by Stexinator** [comment]
Everything besides the migration (weapon, armor) can be tested on https://github.com/Stexinator/TheWitcherTRPG/tree/feature/item_data_types

**Comment by Stexinator** [comment]
This is ready for testing

**Comment by Stexinator** [comment]
@moliloo @TillTHMAcc can you test it till sunday?

**Comment by moliloo** [comment]
Sorry for the late comment, but i will write here what i test and let you know some bugs

### Character Actor
#### Fine
- Drag the container to the sheet
- Edit container inside the sheet
- Drag container where is inside the sheet to she chat
#### Problems
- I can't create a container item in the sheet, in valuables i just cant create valuables

### Monster Actor
#### Problems
- The container is undraggable to the sheet, but it isn't hidden in the sheet because i was looking to the console and nothing happens there

### Loot Actor
#### Problems
- Draggable but its hidden, looking in the console the item was created, i put weight in the container and the loot max weight show the container weight

Because i can't see the container in the sheet i try drag every item type, every type is draggble but not every type is showing, i will list what is hidden or neither for let you know

| Hidden Items  | Showing Items |
| ------------- | ------------- |
| Content Cell  | Content Cell  |
| Content Cell  |   |
| Content Cell  | Content Cell  |
| Content Cell  |   |
| Content Cell  | Content Cell  |
| Content Cell  |   |

**Comment by moliloo** [comment]
Sorry for the late comment, but i will write here what i tested and let you know some bugs

## Character Actor
### Fine
- Drag the container to the sheet
- Edit container inside the sheet
- Drag container where is inside the sheet to she chat
### Problems
- I can't create a container item in the sheet, in valuables i just cant create valuables

## Monster Actor
### Problems
- The container is undraggable to the sheet, but it isn't hidden in the sheet because i was looking to the console and nothing happens there

## Loot Actor
### Problems
- Draggable but its hidden, looking in the console the item was created, i put weight in the container and the loot max weight show the container weight

Because i can't see the container in the sheet i try drag every item type, every type is draggble but not every type is showing, i will list what is hidden or neither for let you know

| Hidden Items | Showing Items|
| ------------- | ------------- |
| Alchemical | Armor |
| Container | Enhancement (Armor type) |
| Diagrams | Components |
| Effects | Valuable |
| Enhancement (Weapon type) | Weapons |
| Mount | Rune |
| Mutagens | Glyph |
| Note |   |
| Profession |   |
| Spell |   |

### Bugs
- Selecting a input in this actor a error is showing in the console
```error
Uncaught TypeError:                                      WitcherLootSheet.js:114
this._onFocusIn is not a function
    at HTMLInputElement.<anonymous> (WitcherLootSheet.js:114:43)
    at HTMLInputElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
    at Object.trigger (jquery.min.js:2:71790)
    at Object.simulate (jquery.min.js:2:72293)
    at HTMLDocument.i (jquery.min.js:2:72582)
```

**Comment by Stexinator** [comment]
For the actor sheet problem:
The container is it own itemtype and not a valuable. So you have to create it as a stand-alone item.
Creating it inside the sheet I could add, but then the section need to be always shown. I will ponder about it :)

**Comment by Stexinator** [comment]
The hidden items will be extracted to another story. The sorting of the loot is off quite general and I need to take a look at it in separation
