### ISSUE TITLE
Weapon Effects

### ISSUE THREAD

**Issue by Siryphas** [Stexinator/TheWitcherTRPG#94]
I know the damage automates the roll for Percentage based effects, like Bleed and Poison, but things like Ablation, Armor Piercing, and Improved Armor Piercing still mostly have to be handled manually. Is there any way to automate more weapon effects?

**Comment by Stexinator** [comment]
- [ ] Ablation
- [ ] Armor Piercing
- [ ] Improved Armor Piercing
- [ ] Balanced -> Will not be added until automated crits are added
- [ ] Non-lethal -> Currently no use case

**Comment by Siryphas** [comment]
Non-Lethal would actually be very helpful. My players like to make ample use of the Teaching Mechanic. They usually do PvP for "sparing." Normally, they just do damage as normal then reset their HP and Armor back up to where it was before that match, but having weapons deal damage to Stamina would be very useful

**Comment by Stexinator** [comment]
Non-Lethal as a weapon ability just allows to do non-lethal attacks without penalty. So there is currently no benefit for it. Adding an apply non-lethal option to the context menu would be the way to go for your use case, but that belongs into another issue :)

**Comment by Siryphas** [comment]
Non-lethal damage should go to Stamina instead of HP

**Comment by Stexinator** [comment]
@moliloo this can also be tested on the dev branch. I had to rework large chunks of the weapon automation. So its best to test the whole process also without the new attributes

**Comment by Stexinator** [comment]
@pedroaugustobt are you also ready to start testing?

**Comment by pedroaugustobt** [comment]
> @pedroaugustobt are you also ready to start testing?

Of course

**Comment by pedroaugustobt** [comment]
@Stexinator 
Feedback TheWitcherTRPG - Features
1st When a Derived Stat is changed, Adrenaline resets;
2nd Critical Wounds is not working, when clicking to add the critical wound, nothing happens;
3rd Ablation and Improved Armor Piercing damage is not decreasing a monster's armor after applying damage (it only decreases if the armor is placed in the monsters' new armor tab, not the old one), but it works normally for created armor;
4th It is not possible to drag the effects of the weapon attack, it appears in the chat but I cannot drag it to the token;
5th Healing on an ally is not applied after selecting him by target.

**Comment by Stexinator** [comment]
3) is expected due to natural armor not ablating
4) is not yet implemented, there are other issues for it

**Comment by Stexinator** [comment]
2. is fixed

**Comment by moliloo** [comment]
I tested the three effects you added and works fine

- Ablating effects reduces the armor sp with the number displayed in the chat;
- Armor Piercing ignores the resistance in the armor;
- Imp. Armor Piercing ignores the resistance and halve the sp

I see you added a select option to the effects, can you explain how this work? If you plan to add a scrip to add the effect in the token or something like this, because i dont understanded the feature
| Weapon Edit | Weapon Chat|
|--------|--------|
| ![](https://media.discordapp.net/attachments/725195811096363090/1241569221352357969/1241567944211824680remix-1716083567346.png?ex=664aacf1&is=66495b71&hm=d1d0e2e3411d824f1cb4b2eae8fe8035271eb67062b385cc3d6111beab7e1322&=&format=webp&quality=lossless&width=378&height=350) |  ![](https://media.discordapp.net/attachments/725195811096363090/1241569160040026212/1241567968987713536remix-1716083553260.png?ex=664aace2&is=66495b62&hm=7165fdb4ff2b769fbc092cec5a205b66c9540dab05633391e8c1b82cd1ecca5b&=&format=webp&quality=lossless&width=430&height=350) |

**Comment by Stexinator** [comment]
You are right, currently it only puts it out in the chat card, but in the feature at least the GM should be able to apply the status from there
